import Head from 'next/head';

function Head_tag() {
    return (
        <Head>
            <title>Profile</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
)}

export default Head_tag;

